Gh 69 add rfs and taxonomies/sb
Kentico/xperience-by-kentico-training-guides pull request #71
Opened 2024-08-27 18:03 UTC by kentico-matthews

# Motivation

Add starting state for reusable field schema and taxonomy guides

2024-08-28 20:48 UTC, dominikag2 requested changes
I left some comments on individual files, here's a few more global things I observed:

- **ArticleSchemaTaxonomy**: I would rename the taxonomy field to ArticleSchemaCategory.
I'd also change the field caption to "Category" - to match the Taxonomy's name. It's also clearer from the UX perspective for the editor and less generic than Tags. 'Tags' in my mind evokes that I can tag it however I want, but in this case, editor can only chose from within the Article category.

- Empty article pages (e.g., About confiers) - are they empty on purpose?
I assume those are prepared to display content items of the new types. I think it would look better if they contained "old" articles. I was imagining in the guide you'd have the reader recreate some of these old ones. If you have a different view, let's discuss.

- We said we will rename the Featured news to Featured articles, but it's still showing up with the old name for me - it seems the registration needs to be updated.
Also, when I try adding it in PageBuilder, I get an error like this: Message: The view 'Components/FeaturedArticleWidget/~/Features/Articles/Widgets/FeaturedArticle/FeaturedArticleWidget.cshtml' was not found. The following locations were searched:
~/Features/Articles/Widgets/FeaturedArticle/FeaturedArticleWidget.cshtml"

- Separate thing I noticed in SB (I don't think you added it now) - Under ste "Store" page in the tree we have two empty product pages. Do you remember if any of our guides rely on them existing? If not, I'd like for us to get rid of them. In my quick search I don't see anything, but it's better if we both double-check.

- The Interview content type in admin has an "InterviewRespondantName" field, but the Interview.generated.cs has an 'IntervieweeName' instead.

2024-08-28 20:48 UTC, dominikag2 commented on src/TrainingGuides.Web/Features/Articles/Widgets/ArticleList/ArticleListWidgetProperties.cs
> +    public string OrderBy { get; set; } = "NewstFirst";
NewestFirst (typo)

2024-08-28 20:48 UTC, dominikag2 commented on src/TrainingGuides.Web/Features/Articles/Widgets/ArticleList/ArticleListWidgetProperties.cs
> +    public IEnumerable<WebPageRelatedItem>? ContentTreeSection { get; set; }
According to our new conventions this should be not nullable and with an initial value (I realize it probably got overlooked by me):
public IEnumerable<WebPageRelatedItem> ContentTreeSection { get; set; } = Enumerable.Empty<WebPageRelatedItem>();

2024-08-28 20:48 UTC, dominikag2 commented on src/TrainingGuides.Web/Features/Articles/Widgets/ArticleList/ArticleListWidgetProperties.cs
> +using System.ComponentModel;
this using looks redundant

2024-08-28 20:48 UTC, dominikag2 commented on src/TrainingGuides.Web/Features/Articles/Widgets/ArticleList/ArticleListWidgetProperties.cs
> +    public string OrderBy { get; set; } = "NewstFirst";
Since we decided to not use the dropdown provider, do you think it would make sense to at least make these values constants?

2024-08-28 20:48 UTC, dominikag2 commented on src/TrainingGuides.Web/Features/Articles/Widgets/ArticleList/FeaturedArticle/FeaturedArticleWidgetProperties.cs
> +    public IEnumerable<WebPageRelatedItem> Article { get; set; } = null!;
Another leftover that must have gotten overlooked previously. Should be initialized to an empty enumerable: = Enumerable.Empty<WebPageRelatedItem>();

2024-08-28 20:48 UTC, dominikag2 commented on src/TrainingGuides.Web/Features/Shared/Models/WidgetViewModel.cs
> +public abstract class WidgetViewModel
Since we're adding this class, we should consider small wording adjustment in this guide: https://docs.kentico.com/guides/development/page-builder/define-advanced-widget#create-the-widget-view-model
It has the reader create the WidgetViewModel if the advanced widget is their first. 
Now if they are following along from main branch, the abstract class will already be there.

2024-08-29 14:55 UTC, kentico-matthews commented
> * Empty article pages (e.g., About confiers) - are they empty on purpose?
>   I assume those are prepared to display content items of the new types. I think it would look better if they contained "old" articles. I was imagining in the guide you'd have the reader recreate some of these old ones. If you have a different view, let's discuss.

By empty, do you mean the data is missing on the content tab of the page, or from the content hub? in that case it must be some kind of CI issue.

If you just mean that they aren't displaying, that's expected, and i thought it is what we agreed on. Maybe we had different takeaways from our conversation but I thought the point was to eliminate tedious data entry work for people following along with the guide, so all they have to worry about is updating the code.

We can talk about it in our meeting later

2024-08-29 14:56 UTC, kentico-matthews commented
> * Separate thing I noticed in SB (I don't think you added it now) - Under ste "Store" page in the tree we have two empty product pages. Do you remember if any of our guides rely on them existing? If not, I'd like for us to get rid of them. In my quick search I don't see anything, but it's better if we both double-check.

These are used in the page builder guides, where they have to build the page template and widgets that display this data. another case of having the data already exist so that the guide isn't bogged down with data entry.

2024-08-29 15:06 UTC, kentico-matthews commented on src/TrainingGuides.Web/Features/Articles/Widgets/ArticleList/ArticleListWidgetProperties.cs
> +    public string OrderBy { get; set; } = "NewstFirst";
good question.
It feels like a half-measure to me. We've already agreed that we're not demonstrating the dropdown provider best practice on this particular widget to get out of the way of this example. and then we're cluttering up the start of the properties class with stuff used at the bottom, unless we define some extra dedicated static class to hold the constants.

There's also a question of whether using constants instead of the more obvious anti-pattern of having hard-coded strings all over the place would obscure that there is a better alternative.

If someone stumbles upon this code as-is, they'll probably say "Oh I shouldn't hard-code strings like that. I wonder if Kentico has a recommended practice for this." I worry that if we do string constants, it'll seem like that's our recommendation for how to handle dropdowns to anyone who stumbles upon it.

We can discuss in our meeting

2024-08-29 15:59 UTC, kentico-matthews commented
> * We said we will rename the Featured news to Featured articles, but it's still showing up with the old name for me - it seems the registration needs to be updated.
>   Also, when I try adding it in PageBuilder, I get an error like this: Message: The view 'Components/FeaturedArticleWidget/~/Features/Articles/Widgets/FeaturedArticle/FeaturedArticleWidget.cshtml' was not found. The following locations were searched:
>   ~/Features/Articles/Widgets/FeaturedArticle/FeaturedArticleWidget.cshtml"

Good catch, I was searching the solution for FeaturedNews to replace, but I missed the name and description in the registration because of the space.

2024-09-04 21:42 UTC, merged